---
- name: Install python3 packages
  ansible.builtin.package:
    name:
      - python3
      - python3-pip
    state: present

- name: Install influxb-client for python
  ansible.builtin.pip:
    name: influxdb-client
    state: present

- name: Install InfluxDB
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ influxdb_influxdb2_packages }}"
  notify: Restart InfluxDB

- name: Ensure startup config is placed
  ansible.builtin.template:
    src: config.toml.j2
    dest: /etc/influxdb/config.toml
    mode: 0644
    owner: root
    group: root

- name: Ensure InfluxDB is started
  ansible.builtin.service:
    name: influxdb
    state: started
