---
- name: Ensure InfluxDB packages are installed
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ influxdb_influxdb2_packages }}"
  notify: Restart InfluxDB

- name: Ensure startup config is there
  ansible.builtin.template:
    src: config.toml.j2
    dest: /etc/influxdb/config.toml
    mode: 0644
    owner: root
    group: root

- name: Ensure InfluxDB is started
  ansible.builtin.service:
    name: influxdb
    state: started
