---
- name: Ensure admin setup token is definded
  ansible.builtin.fail:
    msg: Variable influxdb2_influxdb2_admin_token is not defined in variables
  when: influxdb2_influxdb2_admin_token == ""

- name: Ensure InfluxDB is set up
  ansible.builtin.command: influx setup \
      --host "{{ influxdb2_influxdb2_host }}" \
      --username "{{ influxdb2_influxdb2_primary_user.name }}" \
      --password "{{ influxdb2_influxdb2_primary_user.password }}" \
      --org "{{ influxdb2_influxdb2_primary_org }}" \
      --bucket "{{ influxdb2_influxdb2_primary_bucket }}" \
      --retention "{{ influxdb2_influxdb2_retention }}" \
      --token "{{ influxdb2_influxdb2_admin_token }}" \
      --force
      {% if not (influxdb2_influxdb2_tls_verify | default(true) | bool) %}
      --skip-verify
      {% endif %}
  register: _influx_setup
  failed_when:
    - _influx_setup.rc != 0
    - '"has already been set up" not in _influx_setup.stderr'
  changed_when: _influx_setup.rc == 0

- name: Manage organizations
  tbauriedel.influxdb2.influxdb2_organization:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    desc: "{{ item.desc | default('') }}"
    token: "{{ item.token }}"
    host: "{{ influxdb2_influxdb2_host }}"
    verify_ssl: "{{ item.verify_ssl | default(true) }}"
  loop: "{{ influxdb2_influxdb2_orgs }}"
  when: influxdb2_influxdb2_orgs | length > 0

- name: Manage buckets
  tbauriedel.influxdb2.influxdb2_bucket:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    desc: "{{ item.desc | default('') }}"
    org: "{{ item.org }}"
    token: "{{ item.token }}"
    host: "{{ influxdb2_influxdb2_host }}"
    verify_ssl: "{{ item.verify_ssl | default(true) }}"
    retention:
      type: "{{ item.retention.type }}"
      everySeconds: "{{ item.retention.everySeconds }}"
      shardGroupDurationSeconds: "{{ item.retention.shardGroupDurationSeconds }}"
  loop: "{{ influxdb2_influxdb2_buckets }}"

- name: Manage auth tokens
  tbauriedel.influxdb2.influxdb2_auth:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    desc: "{{ item.desc | default(omit) }}"
    org: "{{ item.org }}"
    token: "{{ influxdb2_influxdb2_admin_token }}"
    host: "{{ influxdb2_influxdb2_host }}"
    verify_ssl: "{{ item.verify_ssl | default(true) }}"
    permissions: "{{ item.permissions }}"
  loop: "{{ influxdb2_influxdb2_tokens }}"
