---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: "repos-${MOLECULE_DISTRO}"
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
