---
- hosts: all
  become: true
  vars:
    influxdb_influxdb2_admin_token: 12345678abcdefg
    influxdb_influxdb2_buckets:
      - name: foobar1
        state: present
        org: default
        token: "{{ influxdb_influxdb2_admin_token }}"
        host: "{{ influxdb_influxdb2_host }}"
        retention:
          type: 'expire'
          everySeconds: 50000
          shardGroupDurationSeconds: 0

  collections:
    - tbauriedel.influxdb2

  roles:
    - repos
    - influxdb2
