# -*- mode: ruby -*-
# vi: set ft=ruby :
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.hostname = "influxdb-ubuntu"
    ubuntu.vm.box = "bento/ubuntu-20.04"
    ubuntu.vm.network "forwarded_port", guest: 8086, host: 8086
    ubuntu.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
#      ansible.verbose = "vvv"
    end
  end

  config.vm.define "rocky" do |rocky|
    rocky.vm.hostname = "influxdb-rocky"
    rocky.vm.box = "rockylinux/9"
    rocky.vm.network "forwarded_port", guest: 8086, host: 8087
    rocky.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
#      ansible.verbose = "vvv"
    end
  end
end
