- name: Converge
  hosts: all
  pre_tasks:
    # InfluxDB user does not exist on that point. Grant read to others therefore.
    - name: Create influxdb cert dir
      ansible.builtin.file:
        path: "/etc/influxdb/tls"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Generate OpenSSL private key
      community.crypto.openssl_privatekey:
        path: /etc/influxdb/tls/tls.pem
        size: 4096
        owner: root
        group: root
        mode: "0755"

    - name: Generate Self Signed OpenSSL certificate
      community.crypto.x509_certificate:
        path: /etc/influxdb/tls/tls.cert
        privatekey_path: /etc/influxdb/tls/tls.pem
        provider: selfsigned
        owner: root
        group: root
        mode: "0755"

  vars:
    influxdb2_influxdb2_tls_enabled: true
    influxdb2_influxdb2_tls_verify: false
    influxdb2_influxdb2_host: https://localhost:8086
    influxdb2_influxdb2_tls_cert: /etc/influxdb/tls/tls.cert
    influxdb2_influxdb2_tls_key: /etc/influxdb/tls/tls.pem
    influxdb2_influxdb2_admin_token: 123456789abc!
    influxdb2_influxdb2_orgs:
      - name: org1
        desc: "This is a description"
        token: "{{ influxdb2_influxdb2_admin_token }}"
        verify_ssl: false
    influxdb2_influxdb2_force_pip: true

    influxdb2_influxdb2_buckets:
      - name: bucket-1
        desc: "This is a description"
        org: org1
        token: "{{ influxdb2_influxdb2_admin_token }}"
        verify_ssl: false
        retention:
          type: 'expire'
          everySeconds: '60000'
          shardGroupDurationSeconds: '7600'

  collections:
    - tbauriedel.influxdb2

  roles:
    - repos
    - influxdb2
