---
- name: Converge
  hosts: all

  vars:
    influxdb_influxdb2_admin_token: 123456789abc!
    influxdb_influxdb2_orgs:
      - name: org1
        #state: absent
        token: "{{ influxdb_influxdb2_admin_token }}"
        host: http://localhost:8086

    influxdb_influxdb2_buckets:
      - name: bucket-1
        #state: absent
        org: org1
        token: "{{ influxdb_influxdb2_admin_token }}"
        host: "{{ influxdb_influxdb2_host }}"

  collections:
    - tbauriedel.influxdb2

  roles:
    - repos
    - influxdb2
