---
- name: Prepare
  hosts: all
  tasks:
    - name: Ensure python3-requests is installed
      ansible.builtin.pip:
        name: "{{ item }}"
      loop:
        - requests
        - influxdb_client
