---
name: Lint
on:
  push:
    tags:
      - "*"
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v6
      - name: Set up Python 3.
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install test dependencies.
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements-test.txt

      - name: yamllint
        run: |
          yamllint .

      - name: ansible-lint
        run: |
          ansible-lint roles/*
